apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: k8s-controller-datadog-monitor
rules:
- apiGroups:
  - api.datadoghq.com
  resources:
  - '*'
  verbs:
  - '*'
